format = '$all'
add_newline = true
follow_symlinks = true
command_timeout = 1000

[os]
disabled = true

[directory]
read_only = 'ó°Œ¾ '
home_symbol = '~'
style = 'bold fg:cyan'
read_only_style = 'red'

[directory.substitutions]
"notes" = 'ğŸ”» '
"~/lab/sgi" = 'ï„•  SGI'
"~/lab/blender" = 'ó°‚«  blender-lab'
"geometry-book" = 'geometry-book ğŸ“– '
"/Volumes/LITTLEZAB" = 'ğŸ¦¢ LITTLEZAB'
"nix-configuration" = 'ó±„… nix-configuration'
"Library/Mobile Documents/com~apple~CloudDocs" = 'â˜ï¸ iCloud'

[c]
symbol = "î˜ "

[cmake]
disabled = false
symbol = "ó±¥’  "

[conda]
disabled = false
symbol = "ï„Œ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_branch]
symbol = "î‚  "

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = 'âœ˜'
ahead = 'Â»'
behind = 'Â«'
diverged = 'ï˜ '
up_to_date = 'âœ“'
untracked = 'ó°¼ˆ '
modified = '!'
staged = '[++\($count\)](green)'
renamed = 'ó°·®  '
deleted = 'ó°§§ '

[haskell]
symbol = "ó°²’ "

[hostname]
disabled = false
ssh_symbol = 'ğŸŒ '

[julia]
symbol = "î˜¤ "

[lua]
disabled = false
symbol = 'ğŸŒ™ '

[nix_shell]
disabled = false
symbol = 'ó±„… '
format = 'via [â˜ƒï¸  $state( \($name\))](bold blue) '

[ocaml]
symbol = "ğŸª "

[os.symbols]
Macos = 'ó°€µ '
NixOS = 'ó±„… '

[package]
disabled = true
symbol = 'ó°— '

[php]
disabled = false
symbol = "ğŸ˜ "

[direnv]
disabled = false

[python]
disabled = false
symbol = 'ğŸ '

[rust]
disabled = false
symbol = "ğŸ¦€ "

[custom.obsidian]
symbol = "ğŸ‘¾ "
detect_folders = ['.obsidian']
style = 'bold italic dimmed fg:purple'
format = '[$symbol.obsidian ]($style)'

[custom.latex]
symbol = 'â›ºï¸Tá´‡X'
detect_extensions = ['tex', 'bib']
style = 'bold italic dimmed fg:#007C7C'
format = '[$symbol ]($style)'

[custom.cpp]
symbol = "ó°™² "
style = "fg:#86BBD8"
when = "ls src/*.cpp"
detect_extensions = ['cpp', 'hpp']
format = '[$symbol($output) ]($style)'
command = "clang --version | awk 'NR==1 {print $4}'"

[custom.hugo]
symbol = "ğŸ• "
style = "fg:#A05D57"
require_repo = true
detect_files = ['hugo.toml']
format = '[$symbol ]($style)'
